[package]
name = "pitch_controller"
version = "0.1.0"
edition = "2021"

[dependencies]
portmidi = "0.3.0"
sdl2 = "0.35.2"
eframe = { version = "0.26", features = ["wgpu"] }
alsa = "0.7"

[build-dependencies]
sdl2 = "0.35.2"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
